//facts array that contains text worded facts,
const facts = [
    "The human brain contains approximately 86 billion neurons!",
    "Your brain generates about 23 watts of power while awake",
    "Memory is affected by both your emotions and environment",
    "The hippocampus is essential for forming new memories and connecting emotions to those memories",
    "People tend to remember emotionally charged events more clearly than normal events, this is a phenomenom known as 'flashbulb memory'.",
    "Your brain is more active when you're asleep than when you're awake, it also consolidates memories during deep sleep.",
    "The average person can store approximately 1 petabyte (1 million gigabytes) of information in their brain.",
    "Short-term memory can hold about 7 items for about 20 seconds, which is known as 'Miller's Law'.",
    "The brain consumes around 20% of the body's total energy, despite only making up 2% of the body's weight!",
    "Synapses in the brain can transmit signals at speeds of up to 400 km/h!",


    "Neurons in your brain communicate by sending electrical signals to each other.",
    "The brain's prefrontal cortex is responsible for higher cognitive functions, such as decision-making, problem-solving, and self-control, this is also the first thing to stop working correctly if you are tired or drunk",
    "Every time you form a new memory, your brain strengthens synaptic connections between neurons.",
    "Stress can impair memory and the ability to form new memories by affecting the hippocampus.",
    "Research suggests that physical exercise can enhance brain function and improve memory.",
    "The brain's default mode network is most active when you're at rest and daydreaming, allowing your mind to wander.",
    "Your brain's ability to reorganise itself by forming new neural connections is known as neuroplasticity.",
    
    "The 'working memory' system of your brain allows you to hold and manipulate information temporarily for cognitive tasks such as reasoning and comprehension.",
    "The brain's processing power is limited; it can only focus on a small number of things at once.",
    "The blood-brain barrier is a selective barrier that protects the brain from harmful substances in the bloodstream, while allowing essential nutrients to pass through.",
    "A person’s brain can continue developing into their mid-20s, with the prefrontal cortex being the last area to mature.",
    "You can improve your memory and brain health through activities like learning a new language or solving puzzles.",
    "Studies show that people who regularly engage in intellectually stimulating activities such as playing puzzles and games tend to experience a slower rate of cognitive decline in old age.",
    "A person’s sense of smell is closely linked to memory, which is why certain scents can trigger vivid memories.",
    "The average brain weighs about 1.3 to 1.4 kilograms, making up about 2% of your body weight.",
    "Emotions like fear and excitement can enhance your ability to remember certain events, due to the release of adrenaline and other hormones.",
    "The concept of 'muscle memory' involves the brain’s ability to remember motor tasks, which is why repeated practice makes actions easier to perform.",
    "The brain’s ability to process visual information is 60,000 times faster than the ability to process text.",
    "New studies show that we cannot actually multitask. Not men or women!",
    "The human brain is the only organ that can study itself.",


    "Your brain can perform more than 10 quadrillion operations per second!",
    "The average adult human brain is about 75% water, which is why dehydration can negatively affect cognitive performance.",
    "The largest part of your brain, the cerebrum, is responsible for controlling thoughts, memory, emotion, touch, motor skills, vision, breathing, and temperature regulation.",
    "The process of converting short term memories into long term memories is known as memory consolidation, and it primarily happens during sleep.",
    "Each time you recall a memory, it’s slightly altered before it’s stored again, meaning memory is not as static as we often believe. Which is why eye witness testimonys are not always reliable. ",
    "Your brain’s ability to recognise faces is an important skill for social interaction and relies on a specific part of the brain called the fusiform face area (FFA).",
    "When you listen to music, your brain releases dopamine, a neurotransmitter that is responsible for feelings of pleasure and reward.",
    "The brain processes and stores information through both chemical and electrical signals, making it a complex and incredibly fast.",
    "New studies suggest that your brain’s capacity for memory may actually improve as you age, especially if you continue learning new things.",
    "Your sense of touch is directly linked to the brain’s somatosensory cortex, which processes sensations like pressure, pain, and temperature.",
    "Increased levels of the hormone cortisol, which is produced during stress, can impair your ability to form and recall memories.",
    "The brain is more adaptable to changes in youth, but the concept of neuroplasticity allows even older adults to form new neural connections.",
    "The emotional part of your brain, known as the limbic system, helps to store emotionally charged memories, often making them easier to recall.",

    "Memory loss, especially in older adults, can be a result of both biological aging and lifestyle factors like lack of mental stimulation or physical activity.",
    "The process of forgetting, while frustrating, is actually a healthy function of the brain, as it helps to declutter unnecessary or irrelevant information.",
    "Research indicates that the brain may store memories in a way that is more akin to a web of interconnected concepts rather than isolated events.",
    "There are over 100 trillion synaptic connections in the brain, which allow for complex thoughts, emotions, and behaviors.",
    "While the brain may appear to be inactive during deep sleep, it is actually performing essential functions like memory consolidation and waste removal.",
    "The phenomenon of déjà vu is believed to occur when your brain detects a mismatch in the process of recalling a memory, making you feel like you're experiencing something for the second time.",
    "The human brain can be rewired through experience, which is why you can train your brain to improve cognitive abilities like memory and focus.",
    "The prefrontal cortex is responsible for controlling impulses and emotions, and it is the last part of the brain to fully mature.",
    "Research has shown that laughing can improve cognitive function by reducing stress and increasing blood flow to the brain."

];
