let words = [
    { word: "addition", hint: "The process of adding numbers" },
    { word: "meeting", hint: "Event in which people come together" },
    { word: "number", hint: "Maths symbol used for counting" },
    { word: "exchange", hint: "The act of trading" },
    { word: "canvas", hint: "Fabric for oil painting" },
    { word: "garden", hint: "Space for planting flowers" },
    { word: "position", hint: "Location of someone or something" },
    { word: "feather", hint: "Hair-like outer covering of a bird" },
    { word: "comfort", hint: "A pleasant feeling of relaxation" },
    { word: "tongue", hint: "The muscular organ of the mouth" },

    { word: "expansion", hint: "The process of increasing or growing" },
    { word: "country", hint: "A politically identified region" },
    { word: "group", hint: "A number of objects or persons" },
    { word: "taste", hint: "Responsible for detecting flavour" },
    { word: "field", hint: "Area of land for farming" },
    { word: "needle", hint: "A thin and sharp metal pin" },
    { word: "expert", hint: "Person with extensive knowledge in a subject" },
    { word: "statement", hint: "A declaration of something" },
    { word: "second", hint: "One-sixtieth of a minute" },
    { word: "library", hint: "Place containing a collection of books" },

    { word: "teacher", hint: "A person who educates others" },
    { word: "clock", hint: "An instrument for measuring and showing time" },
    { word: "bicycle", hint: "A two-wheeled vehicle powered by pedalling" },
    { word: "water", hint: "Clear liquid essential for life" },
    { word: "mountain", hint: "The Sugar Loaf isn't one" },
    { word: "hospital", hint: "A place where sick or injured people go" },
    { word: "window", hint: "An opening in a wall, usually with glass" },
    { word: "computer", hint: "An electronic device for processing data" },
    { word: "bridge", hint: "A structure built to span a gap or obstacle" },
    { word: "football", hint: "A sport played with a round ball between two teams" },

    { word: "pen", hint: "A tool used for writing with ink" },
    { word: "tree", hint: "A tall plant with a trunk and branches" },
    { word: "school", hint: "A place where people go to learn" },
    { word: "rain", hint: "Water that falls from the sky" },
    { word: "ocean", hint: "A large body of salt water" },
    { word: "camera", hint: "A device for taking photographs or videos" },
    { word: "keyboard", hint: "A set of keys used to type on a computer" },
    { word: "train", hint: "A form of transport that runs on tracks" },
    { word: "book", hint: "A set of written or printed pages" },
    { word: "apple", hint: "A round fruit with red or green skin" },

    { word: "car", hint: "A motor vehicle with four wheels used for transport" },
    { word: "street", hint: "A public road in a city or town" },
    { word: "chicken", hint: "A domesticated bird raised for its eggs and meat" },
    { word: "sun", hint: "The star at the centre of our solar system" },
    { word: "sand", hint: "Tiny particles of rock commonly found on beaches" },
    { word: "shoes", hint: "Footwear worn to protect and cover the feet" },
    { word: "clock", hint: "A device for telling time" },
    { word: "airplane", hint: "A vehicle capable of flying, used for air travel" },
    { word: "boat", hint: "A small vessel used for travelling over water" },
    { word: "forest", hint: "A large area covered with trees" },

    { word: "piano", hint: "A musical instrument with black and white keys" },
    { word: "mountain", hint: "A large natural elevation of the earth's surface" },
    { word: "plane", hint: "A vehicle that flies in the sky" },
    { word: "glove", hint: "A piece of clothing worn on the hand" },
    { word: "socks", hint: "You put them on before your shoes" },
    { word: "planet", hint: "A celestial body that orbits a star" },
    { word: "ocean", hint: "A vast body of salt water that covers most of the earth's surface" },
    { word: "stadium", hint: "A large venue for sporting events" },
    { word: "star", hint: "A massive, luminous ball of gas in space" },
    { word: "volcano", hint: "Sugar Loaf is a dormant..." },

    { word: "air", hint: "Invisible gasses that we breathe" },
    { word: "diamond", hint: "A precious, hard gemstone often used in jewelry" },
    { word: "whale", hint: "A large marine mammal" },
    { word: "alphabet", hint: "A set of letters used to write a language" },
    { word: "chocolate", hint: "A sweet treat made from cocoa" },
    { word: "mirror", hint: "A reflective surface that shows an image" },
    { word: "zebra", hint: "An animal with black and white stripes" },
    { word: "gym", hint: "A place for physical exercise and fitness" },
    { word: "moon", hint: "Earth's natural satellite" },
    { word: "guitar", hint: "A musical instrument with six strings" },

    { word: "elephant", hint: "A large land mammal with a trunk" },
    { word: "onion", hint: "They make you cry" },
    { word: "beach", hint: "A sandy area by the ocean" },
    { word: "cloud", hint: "A mass of water vapor in the sky" },
    { word: "island", hint: "A piece of land surrounded by water" },
    { word: "sunflower", hint: "A tall plant with a large yellow flower" },
    { word: "rainbow", hint: "A colorful arc formed after rain" },
    { word: "lighthouse", hint: "A tall tower with a light to guide ships" },
    { word: "compass", hint: "An instrument for finding directions" },
    { word: "quartz", hint: "A mineral used in electronic watches" },

    { word: "carrot", hint: "An orange vegetable with a crunchy texture" },
    { word: "rocket", hint: "A vehicle designed to travel in space" },
    { word: "candle", hint: "A wax stick that provides light when burned" },
    { word: "pyramid", hint: "A triangular shaped ancient structure" },
    { word: "harbor", hint: "A sheltered body of water for ships" },
    { word: "cheetah", hint: "The fastest land animal" },
    { word: "pencil", hint: "A tool used for writing or drawing" },
    { word: "puppy", hint: "A young dog" },
    { word: "squirrel", hint: "A cute rat" },
    { word: "giraffe", hint: "A tall animal with a long neck and spots" },

    { word: "telescope", hint: "An instrument for viewing distant objects" },
    { word: "snowflake", hint: "A tiny crystal of frozen water" },
    { word: "cactus", hint: "A desert plant with spines" },
    { word: "ladder", hint: "A tool used to climb up or down" },
    { word: "key", hint: "A small device used to open locks" },
    { word: "jungle", hint: "A dense tropical forest" },
    { word: "tower", hint: "A tall narrow building" },
    { word: "skyscraper", hint: "A very tall building" },
    { word: "whistle", hint: "A small device that makes a sound when blown" },
    { word: "sandcastle", hint: "A sculpture made from sand" },

    { word: "turtle", hint: "A slow moving reptile with a shell" },
    { word: "fireplace", hint: "A place for a fire inside a house" },
    { word: "forest", hint: "A large area covered by trees" },
    { word: "train", hint: "A mode of transport running on tracks" },
    { word: "iceberg", hint: "A large mass of ice floating in the sea" },
    { word: "penguin", hint: "A flightless bird that lives in cold climates" },
    { word: "stethoscope", hint: "A medical instrument used to listen to heartbeats" },
    { word: "sailboat", hint: "A boat propelled by sails" },
    { word: "balloon", hint: "A flexible container filled with air or gas" },
    { word: "microscope", hint: "Used for looking at small things" }

];
